[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wexample-wex-addon-app"
version = "0.0.10"
description = "App management with wex"
readme = { file = "README.md", content-type = "text/markdown" }
authors = [{name = "weeger", email = "contact@wexample.com"}]
license = { text = "MIT" }
requires-python = ">=3.6"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "wexample-wex-core",
]

[project.urls]
homepage = "https://github.com/wexample/python-wex-addon-app"
