services:
  default:
    stdin_open: ${DOCKER_COMPOSE_STDIN_OPEN:-true}
    tty: ${DOCKER_COMPOSE_TTY:-true}
    restart: unless-stopped
    environment:
      - MANAGED_APP_ENV=${APP_ENV}
    networks:
      - wex_net
