services:
  proxy:
    image: nginxproxy/nginx-proxy:1.3
    container_name: ${APP_PROJECT_NAME}_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${APP_PATH}proxy/certs:/etc/nginx/certs:ro
      - ${APP_PATH}proxy/logs:/var/log/nginx
      - ${APP_PATH}proxy/vhost.d:/etc/nginx/vhost.d
      - ${APP_PATH}proxy/html:/usr/share/nginx/html
      - ${APP_PATH}proxy/wex.conf:/etc/nginx/conf.d/wex.conf
    privileged: true
    extends:
      file: ${SERVICE_DEFAULT_COMPOSE}
      service: default
